<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Panduan Bantuan Sistem Admin (Contextual Help System)
    |--------------------------------------------------------------------------
    |
    | Berisi seluruh materi bantuan operasional dalam Bahasa Indonesia yang
    | mudah dipahami oleh administrator usia 40–50 tahun.
    |
    */

    'pages' => [
        'dashboard' => [
            'id' => 'dashboard',
            'pattern' => ['dashboard', 'dashboard/*'],
            'title' => 'Dashboard Presensi',
            'subtitle' => 'Pusat ringkasan kehadiran harian dan grafik aktivitas operasional',
            'icon' => 'ti ti-layout-dashboard',
            'badge' => 'Halaman Utama',
            'about' => 'Halaman Dashboard adalah pusat pemantauan utama untuk melihat rangkuman kehadiran seluruh karyawan pada hari ini secara langsung. Di sini Anda dapat mengetahui berapa karyawan yang hadir, terlambat, izin, sakit, cuti, serta melihat pengajuan izin yang membutuhkan persetujuan.',
            'actions' => [
                'Memantau jumlah karyawan yang hadir tepat waktu, terlambat, izin, sakit, dan cuti hari ini.',
                'Melihat grafik tren kehadiran selama 7 hari terakhir.',
                'Mengetahui komposisi persentase kehadiran seluruh outlet/cabang.',
                'Melihat antrean pengajuan izin terbaru yang menunggu persetujuan Admin.',
                'Melihat daftar aktivitas karyawan yang baru saja melakukan presensi masuk atau pulang lengkap dengan foto dan jam.',
                'Mengklik kartu statistik untuk melihat daftar nama karyawan secara terperinci.',
            ],
            'steps' => [
                'Pilih tanggal di bagian atas jika Anda ingin melihat rangkuman kehadiran pada hari lain.',
                'Pilih cabang atau departemen pada menu pilihan (filter) jika ingin membatasi tampilan hanya untuk cabang tertentu.',
                'Perhatikan 4 Kartu Statistik Utama di bagian atas untuk melihat kondisi kehadiran secara cepat.',
                'Klik salah satu kartu angka (misal: Hadir Hari Ini atau Terlambat) untuk membuka jendela kecil yang menampilkan daftar nama karyawan bersangkutan.',
                'Gulir layar ke bawah untuk melihat antrean pengajuan izin yang belum diperiksa, lalu klik pengajuan tersebut untuk segera memprosesnya.',
            ],
            'components' => [
                'Pilihan Tanggal' => 'Digunakan untuk memilih tanggal tertentu. Sistem akan langsung memperbarui seluruh data sesuai tanggal yang Anda pilih.',
                'Pilihan Cabang & Departemen' => 'Digunakan untuk menyaring data agar hanya menampilkan staf pada cabang atau divisi tertentu.',
                'Kartu Statistik (Angka Besar)' => 'Menampilkan ringkasan jumlah karyawan aktif, total hadir, terlambat, dan yang perlu tindakan persetujuan.',
                'Grafik Tren 7 Hari' => 'Bagan garis yang memperlihatkan perbandingan antara karyawan yang datang tepat waktu dan yang terlambat selama sepekan.',
                'Aktivitas Presensi Terbaru' => 'Daftar nama, foto selfie, dan jam absen dari karyawan yang baru saja melakukan presensi.',
            ],
            'tips' => [
                'Periksa kartu "Perlu Tindakan" setiap pagi untuk memastikan tidak ada pengajuan izin staf yang tertunda.',
                'Gunakan filter cabang jika perusahaan Anda memiliki banyak outlet agar data lebih fokus dan mudah dibaca.',
                'Jika ingin memperbarui angka terbaru, Anda cukup memuat ulang halaman dengan menekan tombol segarkan di peramban web.',
            ],
            'warnings' => null,
        ],

        'karyawan' => [
            'id' => 'karyawan',
            'pattern' => ['karyawan', 'karyawan/*'],
            'exclude_pattern' => ['karyawan/*/show'],
            'title' => 'Data Karyawan',
            'subtitle' => 'Pengelolaan data profil, penempatan outlet, dan status staf',
            'icon' => 'ti ti-users',
            'badge' => 'Data Master',
            'about' => 'Halaman Data Karyawan digunakan untuk melihat dan mengelola seluruh informasi karyawan yang terdaftar di perusahaan, mulai dari nama lengkap, NIK, outlet tempat bertugas, departemen, shift kerja harian, hingga status akun aplikasi mobile.',
            'actions' => [
                'Mencari karyawan berdasarkan nama lengkap atau nomor NIK.',
                'Menyaring data berdasarkan cabang outlet, departemen, atau jabatan.',
                'Menambah data karyawan baru ke dalam sistem.',
                'Melihat detail profil lengkap karyawan dan data wajah biometrik.',
                'Mengunduh data seluruh karyawan ke dalam berkas Microsoft Excel.',
                'Memeriksa status akun aplikasi mobile dan pengaturan kunci GPS/Shift karyawan.',
            ],
            'steps' => [
                'Ketik nama atau NIK karyawan pada kolom pencarian di bagian atas, lalu tekan tombol "Cari Data".',
                'Gunakan pilihan Cabang, Departemen, atau Jabatan untuk membatasi tampilan sesuai kebutuhan.',
                'Klik tombol "Tambah Karyawan" di pojok kanan atas jika ingin mendaftarkan karyawan baru.',
                'Pada tabel data, klik tombol "Detail" di baris karyawan yang diinginkan untuk melihat data lengkap, membuat akun mobile, atau mengatur foto pengenalan wajah.',
                'Jika ingin menyimpan data ke komputer, klik tombol "Export Excel".',
            ],
            'components' => [
                'Kolom Pencarian' => 'Ketik sebagian atau nama lengkap maupun NIK karyawan untuk menemukan data dengan cepat.',
                'Filter Cabang & Departemen' => 'Pilihan untuk menyaring staf sesuai tempat penugasan dan divisinya.',
                'Tombol Tambah Karyawan' => 'Membuka formulir pendaftaran staf baru (nama, cabang, departemen, shift kerja, dan tanggal bergabung).',
                'Tombol Export Excel' => 'Mengunduh seluruh daftar karyawan yang sesuai dengan filter ke dalam file spreadsheet Excel.',
                'Badge Status Aktif / Nonaktif' => 'Warna hijau menandakan karyawan masih bekerja aktif, sedangkan merah menandakan karyawan sudah dinonaktifkan.',
                'Badge Akun Mobile' => 'Menandakan apakah karyawan sudah memiliki akun untuk login di aplikasi handphone atau belum.',
                'Indikator Kunci GPS & Shift' => 'Ikon gembok hijau berarti karyawan terkunci wajib absen di radius outlet dan shift yang ditentukan.',
            ],
            'tips' => [
                'Gunakan kolom pencarian sebelum mencari baris demi baris di dalam tabel agar lebih menghemat waktu.',
                'Setelah menambah data karyawan baru, jangan lupa membuka tombol "Detail" untuk mendaftarkan foto wajah dan membuatkan akun mobile bagi karyawan tersebut.',
            ],
            'warnings' => 'Sebelum menonaktifkan status karyawan, pastikan karyawan yang dipilih sudah benar agar tidak mengganggu pencatatan kehadiran yang sedang berjalan.',
        ],

        'karyawan_detail' => [
            'id' => 'karyawan_detail',
            'pattern' => ['karyawan/*/show'],
            'title' => 'Detail Profil & Biometrik Karyawan',
            'subtitle' => 'Informasi lengkap staf, akun login mobile, dan foto pengenalan wajah',
            'icon' => 'ti ti-id',
            'badge' => 'Profil Staf',
            'about' => 'Halaman Detail Karyawan menampilkan informasi menyeluruh tentang satu karyawan tertentu. Di halaman ini Anda dapat memperbarui profil karyawan, membuat atau mereset akun login aplikasi mobile, serta mengelola dataset foto wajah untuk pengenalan wajah saat absen.',
            'actions' => [
                'Melihat informasi lengkap staf, tanggal masuk kerja, lama masa kerja, dan shift utama.',
                'Mengubah (edit) data profil staf seperti nama, kontak, cabang, dan departemen.',
                'Membuat akun login aplikasi mobile untuk karyawan yang baru bergabung.',
                'Mereset akun login mobile karyawan jika karyawan lupa akun atau ganti perangkat.',
                'Melihat foto-foto pengenalan wajah (Face Recognition) yang sudah terdaftar.',
                'Menambahkan foto wajah baru karyawan menggunakan kamera atau unggah berkas.',
                'Menghapus dataset foto wajah jika karyawan ingin memperbarui rekaman wajah.',
            ],
            'steps' => [
                'Periksa kartu profil di bagian atas untuk melihat rangkuman identitas dan status staf.',
                'Jika karyawan belum memiliki akun login, klik tombol "Buat Akun Mobile" di bawah profil.',
                'Untuk mengatur wajah presensi, buka tab "Biometrik Wajah", lalu klik "Tambah Foto Wajah" untuk mengambil foto wajah staf yang jelas.',
                'Untuk melihat rincian alamat, telepon, nomor identitas, dan status kunci shift, klik tab "Data Karyawan & Penugasan".',
                'Klik tombol "Kembali ke Daftar" di kiri atas jika sudah selesai mengelola karyawan.',
            ],
            'components' => [
                'Tombol Edit Karyawan' => 'Membuka formulir perubahan data pribadi dan data penempatan karyawan.',
                'Tombol Buat Akun Mobile' => 'Secara otomatis membuatkan username dan kata sandi login agar karyawan dapat masuk ke aplikasi Android/iPhone.',
                'Tab Biometrik Wajah' => 'Tempat mengelola foto referensi wajah yang digunakan sistem kecerdasan buatan untuk mengenali karyawan saat presensi selfie.',
                'Tombol Tambah Foto Wajah' => 'Membuka kamera atau pilihan berkas untuk mendaftarkan foto wajah staf dari berbagai sudut pencahayaan yang baik.',
                'Tab Data Karyawan & Penugasan' => 'Menampilkan nomor HP, alamat tempat tinggal, email, status perkawinan, serta pengaturan kunci GPS dan jam kerja.',
            ],
            'tips' => [
                'Saat mendaftarkan foto wajah staf, pastikan wajah menghadap lurus ke kamera, berada di tempat yang terang, dan tidak menggunakan kacamata hitam atau masker.',
                'Daftarkan minimal 1 hingga 3 foto wajah dengan ekspresi wajar untuk meningkatkan akurasi pengenalan wajah di aplikasi mobile.',
            ],
            'warnings' => 'Tindakan "Reset Akun Mobile" atau "Hapus Semua Dataset Wajah" akan menghapus akses login dan data biometrik staf bersangkutan. Lakukan hanya jika staf benar-benar meminta pembaruan data akun.',
        ],

        'presensi' => [
            'id' => 'presensi',
            'pattern' => ['presensi', 'presensi/*'],
            'exclude_pattern' => ['trackingpresensi', 'trackingpresensi/*'],
            'title' => 'Monitoring Presensi Harian',
            'subtitle' => 'Pemantauan absensi masuk dan pulang serta verifikasi lokasi GPS',
            'icon' => 'ti ti-calendar-check',
            'badge' => 'Kehadiran',
            'about' => 'Halaman Monitoring Presensi digunakan untuk memantau catatan kehadiran seluruh karyawan pada hari kerja tertentu. Anda dapat melihat jam tepatnya karyawan melakukan presensi masuk dan pulang, foto selfie yang diambil, lokasi peta GPS saat absen, serta melakukan perbaikan (koreksi) jam absen jika ada kendala teknis.',
            'actions' => [
                'Memantau daftar kehadiran karyawan secara langsung (real-time).',
                'Menyaring data presensi berdasarkan tanggal tertentu, cabang outlet, dan nama karyawan.',
                'Memfilter data berdasarkan status: Hadir, Terlambat, Tepat Waktu, Izin, Sakit, Cuti, atau Alpa.',
                'Melihat foto selfie karyawan saat melakukan presensi masuk dan pulang.',
                'Melihat titik lokasi koordinat GPS karyawan pada peta saat menekan tombol absen.',
                'Melakukan koreksi presensi (mengubah jam masuk/pulang atau status) jika ada kesalahan.',
                'Menghapus rekaman data presensi tertentu jika terjadi duplikasi atau kekeliruan.',
            ],
            'steps' => [
                'Gunakan kotak "Pilih Tanggal Presensi" untuk menentukan tanggal yang ingin diperiksa.',
                'Pilih cabang pada menu dropdown jika ingin memeriksa outlet tertentu.',
                'Klik tombol "Cari Data" untuk menampilkan daftar presensi.',
                'Klik pada angka jam masuk atau jam pulang karyawan untuk melihat foto bukti selfie dan titik koordinat GPS pada peta.',
                'Jika jam absen karyawan tidak sesuai karena kendala teknis perangkat, klik tombol ikon pensil hijau (Koreksi Presensi) untuk memperbaikinya.',
            ],
            'components' => [
                'Filter Tanggal' => 'Memilih hari kerja yang ingin dipantau catatan absensinya.',
                'Filter Outlet / Cabang' => 'Menyaring daftar staf berdasarkan lokasi cabang tempat bertugas.',
                'Pencarian Nama' => 'Mencari catatan kehadiran staf tertentu secara cepat.',
                'Label Status Kehadiran' => 'Menjelaskan kondisi kehadiran: Hijau (Tepat Waktu), Kuning (Terlambat), Biru (Izin), Jingga (Sakit), Toska (Cuti), Merah (Tidak Hadir).',
                'Foto & Jam Masuk/Pulang' => 'Tautan yang jika diklik akan menampilkan foto wajah saat absen beserta peta lokasi karyawan.',
                'Tombol Koreksi Presensi (Ikon Pensil)' => 'Formulir bantuan untuk Admin agar bisa mengisi jam absen atau mengubah status kehadiran secara manual.',
                'Tombol Hapus Presensi (Ikon Tempat Sampah)' => 'Menghapus data presensi baris tersebut.',
            ],
            'tips' => [
                'Gunakan filter status di bagian atas tabel untuk langsung melihat siapa saja karyawan yang terlambat atau belum hadir hari ini.',
                'Periksa titik koordinat GPS pada peta saat membuka detail presensi untuk memastikan karyawan benar-benar berada di lingkungan kantor/outlet.',
            ],
            'warnings' => 'Menghapus atau mengoreksi presensi akan langsung memengaruhi laporan rekap kehadiran bulanan karyawan. Pastikan Anda memiliki konfirmasi jelas dari staf atau atasan sebelum melakukan perubahan data.',
        ],

        'trackingpresensi' => [
            'id' => 'trackingpresensi',
            'pattern' => ['trackingpresensi', 'trackingpresensi/*'],
            'title' => 'Live Tracking GPS Presensi',
            'subtitle' => 'Pemetaan sebaran lokasi presensi masuk dan pulang di atas peta digital',
            'icon' => 'ti ti-map-pin',
            'badge' => 'Peta GPS',
            'about' => 'Halaman Live Tracking GPS menampilkan peta visual yang memetakan seluruh titik lokasi di mana karyawan melakukan presensi masuk dan pulang. Fitur ini memudahkan Admin untuk melihat sebaran kehadiran staf di berbagai cabang dan memastikan kehadiran dilakukan di lokasi kerja yang sah.',
            'actions' => [
                'Melihat sebaran titik presensi karyawan di atas peta digital secara visual.',
                'Menyaring tampilan peta berdasarkan tanggal presensi dan cabang tertentu.',
                'Mengklik penanda lokasi (pin peta / cluster) untuk melihat rincian nama staf, jam presensi, dan foto.',
                'Memeriksa apakah lokasi presensi karyawan berada di dalam atau di luar lingkaran radius kantor.',
            ],
            'steps' => [
                'Pilih tanggal presensi yang ingin Anda lihat sebaran lokasinya di bagian atas peta.',
                'Pilih cabang outlet jika ingin memperbesar tampilan peta ke wilayah cabang tertentu.',
                'Gunakan tombol (+) dan (-) di sudut peta atau gulirkan roda mouse untuk memperbesar (zoom in) dan memperkecil (zoom out) peta.',
                'Klik lingkaran angka pengelompokan (cluster) untuk memecah titik lokasi staf yang berdekatan.',
                'Klik salah satu penanda pin staf untuk memunculkan jendela keterangan berisi foto selfie, nama staf, cabang, dan jam presensi.',
            ],
            'components' => [
                'Peta Digital Interaktif' => 'Peta layar penuh yang menampilkan kontur jalan dan lokasi presensi.',
                'Penanda Lokasi (Pin)' => 'Titik lokasi fisik saat karyawan menekan tombol absen di handphone mereka.',
                'Lingkaran Cluster' => 'Pengelompokan otomatis titik-titik staf yang berada di area yang sama agar peta tetap rapi dan mudah dibaca.',
                'Jendela Keterangan (Popup)' => 'Kotak informasi berisi foto wajah, jam absen masuk/pulang, dan alamat koordinat saat pin diklik.',
            ],
            'tips' => [
                'Gunakan fitur ini untuk memantau kejujuran lokasi presensi karyawan lapangan atau staf yang ditugaskan di outlet baru.',
                'Jika titik presensi berada jauh di luar cabang, Anda dapat memeriksa kembali apakah staf memiliki izin atau penugasan khusus.',
            ],
            'warnings' => null,
        ],

        'izinabsen' => [
            'id' => 'izinabsen',
            'pattern' => ['izinabsen', 'izinabsen/*'],
            'title' => 'Persetujuan Izin Absen',
            'subtitle' => 'Pemeriksaan dan persetujuan permohonan izin tidak masuk kerja',
            'icon' => 'ti ti-file-description',
            'badge' => 'Pengajuan',
            'about' => 'Halaman Persetujuan Izin Absen digunakan untuk meninjau dan memproses permohonan izin tidak masuk kerja yang diajukan oleh karyawan melalui aplikasi mobile mereka, misalnya karena keperluan mendesak, urusan keluarga, atau keperluan pribadi.',
            'actions' => [
                'Melihat daftar pengajuan permohonan izin absen dari karyawan.',
                'Menyaring pengajuan berdasarkan rentang tanggal, nama karyawan, dan status persetujuan.',
                'Menyetujui (approve) permohonan izin yang memenuhi syarat.',
                'Menolak (reject) permohonan izin yang tidak memenuhi kriteria perusahaan.',
                'Membatalkan status persetujuan yang sebelumnya sudah pernah diberikan jika diperlukan evaluasi ulang.',
                'Membuat permohonan izin secara manual atas nama staf melalui tombol "Tambah Izin".',
            ],
            'steps' => [
                'Gunakan filter status di bagian atas dan pilih "Pending" untuk melihat pengajuan yang belum diproses.',
                'Klik baris pengajuan atau tombol detail untuk membaca alasan dan tanggal permohonan izin yang diajukan staf.',
                'Jika permohonan disetujui, klik tombol persetujuan (Setujui/Approve). Data presensi karyawan pada tanggal tersebut otomatis dicatat sebagai "Izin".',
                'Jika permohonan tidak diizinkan, klik tombol tolak (Tolak/Reject) dan berikan catatan alasan penolakan jika tersedia.',
                'Gunakan tombol "Batalkan Persetujuan" jika terjadi perubahan keputusan dari manajemen.',
            ],
            'components' => [
                'Filter Tanggal & Status' => 'Memudahkan menemukan pengajuan pada periode tertentu atau menyaring pengajuan yang masih menunggu konfirmasi.',
                'Status Pending (Kuning)' => 'Menandakan permohonan izin baru masuk dan belum diperiksa oleh Admin.',
                'Status Disetujui (Hijau)' => 'Permohonan telah disetujui dan karyawan sah tidak masuk kerja dengan status izin.',
                'Status Ditolak (Merah)' => 'Permohonan tidak disetujui oleh Admin.',
                'Tombol Aksi Persetujuan' => 'Tombol untuk memberikan keputusan persetujuan atau penolakan pengajuan.',
            ],
            'tips' => [
                'Periksa kolom keterangan izin dengan seksama sebelum menekan tombol persetujuan.',
                'Segera proses pengajuan yang berstatus "Pending" agar staf mendapatkan kepastian jadwal kerja di outlet mereka.',
            ],
            'warnings' => 'Pengajuan yang sudah disetujui akan langsung tercatat ke dalam sistem kehadiran dan memotong jam kerja normal. Pastikan Anda sudah berkoordinasi dengan kepala cabang terkait sebelum menyetujui.',
        ],

        'izinsakit' => [
            'id' => 'izinsakit',
            'pattern' => ['izinsakit', 'izinsakit/*'],
            'title' => 'Persetujuan Izin Sakit',
            'subtitle' => 'Pemeriksaan surat keterangan dokter dan persetujuan izin sakit karyawan',
            'icon' => 'ti ti-file-text',
            'badge' => 'Pengajuan',
            'about' => 'Halaman Persetujuan Izin Sakit digunakan untuk memverifikasi laporan ketidakhadiran karyawan karena alasan sakit. Di sini Admin dapat memeriksa bukti foto Surat Izin Dokter (SID) / surat keterangan sakit yang diunggah staf sebelum memberikan persetujuan resmi.',
            'actions' => [
                'Melihat daftar permohonan izin sakit yang diajukan staf.',
                'Membuka dan melihat berkas lampiran Surat Keterangan Dokter (SID) secara langsung.',
                'Menyetujui (approve) izin sakit sehingga status absensi staf tercatat sebagai "Sakit".',
                'Menolak (reject) izin sakit jika lampiran surat dokter tidak valid atau tidak terbaca.',
                'Membatalkan persetujuan yang sudah terlanjur diberikan.',
                'Menambahkan data izin sakit manual jika karyawan menyerahkan surat dokter secara fisik ke kantor.',
            ],
            'steps' => [
                'Buka baris permohonan izin sakit yang berstatus "Pending".',
                'Klik tautan atau tombol "Lihat Surat Dokter / SID" untuk memeriksa keaslian dan tanggal istirahat pada surat dokter yang dilampirkan.',
                'Pastikan tanggal istirahat pada surat dokter sesuai dengan tanggal izin yang diajukan staf.',
                'Klik "Setujui" jika berkas lengkap dan sah. Sistem akan mencatat kehadiran sebagai "Sakit".',
                'Klik "Tolak" jika surat tidak sah, buram, atau tidak memenuhi ketentuan perusahaan.',
            ],
            'components' => [
                'Lampiran Surat Dokter (SID)' => 'Foto atau dokumen surat istirahat dari dokter/klinik yang diunggah oleh karyawan.',
                'Filter Status' => 'Menyaring pengajuan yang masih menunggu verifikasi (Pending), Disetujui, atau Ditolak.',
                'Rentang Tanggal Sakit' => 'Menampilkan hari mulai dan hari selesai istirahat sakit yang diajukan.',
            ],
            'tips' => [
                'Selalu periksa stempel klinik/rumah sakit dan tanda tangan dokter pada foto surat izin sakit yang diunggah.',
                'Jika foto surat dokter buram, mintalah staf mengirimkan foto ulang yang lebih jelas sebelum Anda menyetujui permohonan.',
            ],
            'warnings' => 'Berkas surat izin dokter bersifat rahasia medis pribadi. Gunakan lampiran ini hanya untuk keperluan verifikasi absensi perusahaan.',
        ],

        'izincuti' => [
            'id' => 'izincuti',
            'pattern' => ['izincuti', 'izincuti/*'],
            'title' => 'Persetujuan Cuti Karyawan',
            'subtitle' => 'Pengelolaan permohonan cuti, sisa kuota cuti tahunan, dan cetak form',
            'icon' => 'ti ti-calendar-event',
            'badge' => 'Pengajuan',
            'about' => 'Halaman Persetujuan Cuti Karyawan digunakan untuk meninjau pengajuan cuti staf. Sistem secara otomatis menampilkan sisa kuota hari cuti yang masih dimiliki staf bersangkutan sehingga Admin dapat memastikan jatah cuti mencukupi sebelum memberikan izin.',
            'actions' => [
                'Melihat daftar permohonan cuti tahunan atau cuti khusus dari seluruh karyawan.',
                'Mengecek sisa kuota hari cuti yang dimiliki karyawan secara otomatis.',
                'Menyetujui pengajuan cuti sehingga kuota cuti staf berkurang dan jadwal kehadiran tercatat "Cuti".',
                'Menolak permohonan cuti jika kuota habis atau jadwal operasional outlet sedang padat.',
                'Mencetak berkas Formulir Pengajuan Cuti resmi untuk arsip fisik personalia.',
                'Membatalkan persetujuan cuti jika ada pembatalan cuti dari pihak staf.',
            ],
            'steps' => [
                'Periksa pengajuan yang berstatus "Pending" pada daftar tabel cuti.',
                'Lihat jenis cuti yang diajukan, jumlah hari cuti, dan sisa kuota cuti yang dimiliki karyawan.',
                'Pertimbangkan ketersediaan staf di cabang bersangkutan sebelum menyetujui.',
                'Klik tombol "Setujui" untuk mengesahkan cuti, atau klik "Tolak" jika tidak memungkinkan.',
                'Jika kantor membutuhkan lembar bukti tanda tangan fisik, klik tombol "Cetak Form Cuti" untuk mencetaknya.',
            ],
            'components' => [
                'Jenis Cuti' => 'Kategori cuti yang diambil (misalnya: Cuti Tahunan, Cuti Melahirkan, Cuti Menikah, dll).',
                'Sisa Kuota Cuti' => 'Jumlah hari cuti yang masih tersisa dan berhak digunakan oleh staf pada tahun berjalan.',
                'Lama Hari Cuti' => 'Total hari kerja yang diajukan untuk libur cuti.',
                'Tombol Cetak Cuti' => 'Menghasilkan dokumen resmi formulir izin cuti siap cetak ke printer atau simpan ke PDF.',
            ],
            'tips' => [
                'Periksa sisa kuota cuti karyawan terlebih dahulu sebelum menekan tombol setuju.',
                'Koordinasikan dengan penanggung jawab outlet agar operasional cabang tetap berjalan lancar saat ada staf yang cuti.',
            ],
            'warnings' => 'Menyetujui pengajuan cuti akan langsung memotong sisa saldo kuota cuti tahunan karyawan. Jika permohonan dibatalkan kemudian, gunakan tombol "Batalkan Persetujuan" agar saldo kuota cuti staf dikembalikan oleh sistem.',
        ],

        'dispensasi' => [
            'id' => 'dispensasi',
            'pattern' => ['dispensasi', 'dispensasi/*'],
            'title' => 'Dispensasi Keterlambatan',
            'subtitle' => 'Persetujuan toleransi keterlambatan shift jam masuk kerja',
            'icon' => 'ti ti-clock-check',
            'badge' => 'Pengajuan',
            'about' => 'Halaman Dispensasi Keterlambatan digunakan untuk memberikan izin khusus kepada karyawan yang datang terlambat karena alasan tertentu yang dapat dibenarkan (misalnya: penugasan mendadak dari pimpinan, ban pecah di jalan, atau bencana banjir). Dengan dispensasi ini, keterlambatan staf tidak akan dihitung sebagai denda atau pelanggaran absensi.',
            'actions' => [
                'Melihat daftar permohonan dispensasi keterlambatan yang diajukan staf atau atasan.',
                'Menyetujui dispensasi sehingga status kehadiran staf berubah menjadi "Dispensasi Hadir".',
                'Menolak dispensasi jika alasan keterlambatan tidak dapat diterima perusahaan.',
                'Menambahkan data dispensasi langsung dari sisi Admin.',
                'Menghapus atau membatalkan dispensasi yang telah dibuat.',
            ],
            'steps' => [
                'Periksa daftar permohonan dispensasi yang masuk pada tabel.',
                'Lihat tanggal kejadian, jam kedatangan staf, dan alasan keterlambatan yang disampaikan.',
                'Klik tombol persetujuan (Setujui) jika pimpinan cabang telah menyetujui alasan tersebut.',
                'Status absensi karyawan pada hari itu akan otomatis disesuaikan tanpa potongan keterlambatan.',
            ],
            'components' => [
                'Alasan Dispensasi' => 'Keterangan tertulis penyebab terjadinya keterlambatan.',
                'Status Persetujuan' => 'Kondisi verifikasi apakah dispensasi sudah disahkan atau ditolak oleh Admin.',
                'Shift Terkait' => 'Jam kerja operasional yang mengalami keterlambatan.',
            ],
            'tips' => [
                'Gunakan dispensasi secara bijak dan hanya berikan kepada staf yang memang memiliki alasan kuat dan konfirmasi dari atasan langsung.',
            ],
            'warnings' => 'Pemberian dispensasi akan membebaskan karyawan dari catatan pelanggaran keterlambatan pada rekapitulasi gaji/laporan bulanan.',
        ],

        'harilibur' => [
            'id' => 'harilibur',
            'pattern' => ['harilibur', 'harilibur/*'],
            'title' => 'Hari Libur / Tanggal Merah',
            'subtitle' => 'Pengaturan hari libur nasional dan penetapan jadwal libur khusus staf',
            'icon' => 'ti ti-calendar-off',
            'badge' => 'Jadwal Kerja',
            'about' => 'Halaman Hari Libur digunakan untuk mencatat tanggal merah resmi nasional maupun libur operasional perusahaan. Pada tanggal yang ditetapkan sebagai hari libur, sistem presensi tidak akan menandai staf sebagai alpa/tidak hadir.',
            'actions' => [
                'Melihat kalender daftar hari libur nasional dan libur perusahaan yang sudah terdaftar.',
                'Menambah tanggal hari libur baru lengkap dengan nama keterangan libur.',
                'Mengubah nama atau tanggal hari libur yang sudah ada.',
                'Menetapkan hari libur khusus yang hanya berlaku untuk cabang atau staf tertentu (Atur Karyawan Libur).',
                'Menghapus catatan hari libur jika ada pembatalan.',
            ],
            'steps' => [
                'Klik tombol "Tambah Hari Libur" di pojok kanan atas untuk memasukkan tanggal merah baru.',
                'Pilih tanggal hari libur, masukkan nama keterangan (contoh: "Tahun Baru Imlek"), dan pilih cabang yang berlaku (atau semua cabang).',
                'Klik "Simpan" untuk mendaftarkan hari libur.',
                'Jika ada libur yang hanya berlaku bagi sebagian staf, klik tombol "Atur Karyawan" pada baris hari libur tersebut untuk memilih nama staf bersangkutan.',
            ],
            'components' => [
                'Tabel Hari Libur' => 'Menampilkan daftar tanggal, hari, nama perayaan libur, dan cakupan cabang yang diliburkan.',
                'Tombol Atur Karyawan' => 'Memungkinkan penetapan libur secara fleksibel per individu karyawan.',
                'Tombol Tambah Hari Libur' => 'Formulir untuk menetapkan tanggal merah baru ke dalam kalender kerja sistem.',
            ],
            'tips' => [
                'Daftarkan seluruh tanggal merah dan libur nasional di awal tahun agar perhitungan absensi dan cuti berjalan akurat secara otomatis.',
            ],
            'warnings' => 'Menghapus tanggal libur yang sudah terlewat dapat memicu sistem menandai karyawan yang tidak hadir pada hari itu sebagai tidak masuk kerja (alpa). Berhati-hatilah saat mengubah data hari libur yang lampau.',
        ],

        'cabang' => [
            'id' => 'cabang',
            'pattern' => ['cabang', 'cabang/*'],
            'title' => 'Outlet / Cabang Kantor',
            'subtitle' => 'Pengelolaan data lokasi fisik kantor, koordinat GPS, dan radius presensi',
            'icon' => 'ti ti-building-store',
            'badge' => 'Data Master',
            'about' => 'Halaman Outlet / Cabang digunakan untuk mengelola data seluruh lokasi kerja fisik perusahaan (kantor pusat, cabang, maupun gerai outlet). Di sini Anda mengatur titik koordinat GPS (garis lintang & bujur) serta jarak radius aman (dalam meter) agar karyawan hanya bisa absen saat benar-benar berada di lokasi kerja.',
            'actions' => [
                'Melihat daftar seluruh cabang outlet yang terdaftar di perusahaan.',
                'Menambah cabang kantor atau outlet baru ke dalam sistem.',
                'Mengubah nama cabang, alamat lengkap, nomor telepon, dan penanggung jawab cabang.',
                'Mengatur titik koordinat GPS (Latitude & Longitude) kantor pada peta.',
                'Mengatur batas jarak radius presensi (contoh: 50 meter dari titik kantor).',
                'Menghapus data cabang yang sudah tidak beroperasi lagi.',
            ],
            'steps' => [
                'Klik tombol "Tambah Cabang" untuk mendaftarkan outlet baru.',
                'Isi kode cabang yang unik, nama cabang, dan alamat lengkap outlet.',
                'Tentukan titik koordinat GPS kantor dengan mengetik angka koordinat atau menggeser pin lokasi pada peta.',
                'Tentukan angka radius toleransi dalam satuan meter (misal: 30 meter atau 50 meter).',
                'Klik "Simpan" agar outlet baru siap digunakan oleh staf di aplikasi mobile.',
            ],
            'components' => [
                'Titik Koordinat GPS' => 'Angka garis lintang (latitude) dan bujur (longitude) yang menunjukkan lokasi fisik kantor secara presisi di peta dunia.',
                'Radius Absen (Meter)' => 'Jarak lingkaran maksimal dari titik tengah kantor di mana karyawan diperbolehkan menekan tombol absensi.',
                'Kode Cabang' => 'Kode unik pengenal outlet (misalnya: CB01, PUSAT, GKB, dll).',
            ],
            'tips' => [
                'Untuk mendapatkan titik koordinat GPS kantor dengan akurat, Anda bisa membuka Google Maps saat berada di kantor, klik kanan pada titik lokasi, lalu salin angka koordinatnya.',
                'Gunakan radius yang wajar (antara 30 hingga 50 meter) untuk mengantisipasi ketidakakuratan GPS pada telepon genggam tertentu saat berada di dalam ruangan.',
            ],
            'warnings' => 'Mengubah titik koordinat atau memperkecil radius terlalu sempit (misal di bawah 10 meter) dapat menyebabkan karyawan kesulitan melakukan presensi karena sinyal GPS handphone yang bergeser.',
        ],

        'departemen' => [
            'id' => 'departemen',
            'pattern' => ['departemen', 'departemen/*'],
            'title' => 'Data Master Departemen',
            'subtitle' => 'Pengelolaan struktur divisi dan bagian kerja operasional',
            'icon' => 'ti ti-sitemap',
            'badge' => 'Data Master',
            'about' => 'Halaman Departemen digunakan untuk mengelola nama-nama divisi atau bagian kerja di perusahaan (seperti Operasional, Dapur, Pelayanan, Keuangan, Personalia, dan Pemasaran). Data ini digunakan untuk mengelompokkan karyawan dan laporan kehadiran.',
            'actions' => [
                'Melihat seluruh divisi/departemen kerja yang terdaftar.',
                'Menambah departemen baru ke dalam sistem.',
                'Mengubah kode atau nama departemen yang sudah ada.',
                'Menghapus departemen yang sudah tidak digunakan.',
            ],
            'steps' => [
                'Klik tombol "Tambah Departemen" di kanan atas.',
                'Masukkan kode departemen (misalnya: OPR, KEU, HRD) dan nama lengkap departemen.',
                'Klik tombol "Simpan" untuk menambahkan ke dalam daftar.',
            ],
            'components' => [
                'Kode Departemen' => 'Singkatan unik divisi kerja.',
                'Nama Departemen' => 'Nama lengkap bagian atau divisi kerja perusahaan.',
            ],
            'tips' => [
                'Gunakan singkatan kode yang mudah diingat dan konsisten di seluruh perusahaan.',
            ],
            'warnings' => 'Departemen yang masih memiliki karyawan aktif di dalamnya sebaiknya tidak dihapus agar tidak merusak pengelompokan data staf.',
        ],

        'jabatan' => [
            'id' => 'jabatan',
            'pattern' => ['jabatan', 'jabatan/*'],
            'title' => 'Data Master Jabatan',
            'subtitle' => 'Pengelolaan struktur tingkat posisi dan profesi kerja karyawan',
            'icon' => 'ti ti-briefcase',
            'badge' => 'Data Master',
            'about' => 'Halaman Jabatan digunakan untuk mengelola daftar posisi pekerjaan staf di perusahaan (misalnya: Manajer Outlet, Supervisor, Barista, Kasir, Koki, Staf Gudang, dan Staf Kebersihan).',
            'actions' => [
                'Melihat daftar posisi jabatan yang berlaku di perusahaan.',
                'Menambah nama posisi jabatan baru.',
                'Mengubah nama atau kode jabatan.',
                'Menghapus jabatan yang sudah tidak digunakan.',
            ],
            'steps' => [
                'Klik tombol "Tambah Jabatan" di kanan atas.',
                'Ketikkan kode jabatan dan nama jabatan yang diinginkan.',
                'Klik "Simpan" untuk menyimpan data ke sistem.',
            ],
            'components' => [
                'Kode Jabatan' => 'Kode unik posisi jabatan.',
                'Nama Jabatan' => 'Nama gelar atau sebutan profesi kerja staf.',
            ],
            'tips' => [
                'Pastikan penamaan jabatan sesuai dengan struktur organisasi resmi perusahaan.',
            ],
            'warnings' => 'Jangan menghapus jabatan yang sedang digunakan oleh karyawan yang masih bekerja aktif.',
        ],

        'cuti' => [
            'id' => 'cuti',
            'pattern' => ['cuti', 'cuti/*'],
            'title' => 'Data Master Jenis Cuti',
            'subtitle' => 'Pengaturan kategori cuti dan jatah kuota hari dalam setahun',
            'icon' => 'ti ti-calendar-stats',
            'badge' => 'Data Master',
            'about' => 'Halaman Jenis Cuti digunakan untuk menentukan kategori cuti yang boleh diambil oleh staf beserta jatah maksimal hari dalam satu tahun kalender (contoh: Cuti Tahunan jatah 12 hari, Cuti Melahirkan 90 hari, Cuti Menikah 3 hari).',
            'actions' => [
                'Melihat daftar jenis cuti yang tersedia bagi karyawan.',
                'Menambahkan jenis cuti baru dengan menentukan jatah kuota hari per tahun.',
                'Mengubah nama jenis cuti atau memperbarui jumlah kuota hari.',
                'Menghapus jenis cuti yang sudah tidak berlaku.',
            ],
            'steps' => [
                'Klik tombol "Tambah Cuti" di bagian atas.',
                'Ketik kode cuti (misal: C01), nama cuti (misal: "Cuti Tahunan"), dan isikan kuota jumlah hari (misal: 12).',
                'Klik "Simpan" untuk mengaktifkan jenis cuti tersebut di aplikasi staf.',
            ],
            'components' => [
                'Kode Cuti' => 'Kode singkatan unik untuk kategori cuti.',
                'Nama Cuti' => 'Nama resmi kategori perizinan libur cuti.',
                'Jumlah Hari (Kuota)' => 'Batas maksimal hari kerja yang dapat diambil staf untuk jenis cuti ini per tahun.',
            ],
            'tips' => [
                'Sesuaikan kuota hari cuti dengan peraturan ketenagakerjaan dan kesepakatan kerja bersama di perusahaan Anda.',
            ],
            'warnings' => 'Mengubah jumlah kuota hari pada jenis cuti yang sedang berjalan akan memengaruhi sisa saldo cuti seluruh karyawan pada tahun ini.',
        ],

        'jamkerja' => [
            'id' => 'jamkerja',
            'pattern' => ['jamkerja', 'jamkerja/*'],
            'title' => 'Shift & Jam Kerja Karyawan',
            'subtitle' => 'Pengaturan jam masuk, jam pulang, dan batas toleransi keterlambatan',
            'icon' => 'ti ti-clock',
            'badge' => 'Jadwal Kerja',
            'about' => 'Halaman Shift & Jam Kerja digunakan untuk mengatur jadwal jam operasional kerja karyawan (misalnya: Shift Pagi dari jam 07:00 s.d 15:00, Shift Siang dari jam 15:00 s.d 23:00). Anda juga dapat menentukan rentang waktu tombol presensi dibuka dan batas menit toleransi keterlambatan.',
            'actions' => [
                'Melihat daftar shift kerja harian yang tersedia di perusahaan.',
                'Menambah pola shift kerja baru (jam masuk, jam pulang, dan waktu istirahat).',
                'Mengatur batas awal mulai absen masuk (agar staf tidak bisa absen terlalu dini).',
                'Mengatur batas akhir absen masuk dan batas toleransi terlambat (dalam menit).',
                'Mengatur batas jam presensi pulang (agar staf tidak bisa absen pulang sebelum waktunya).',
                'Mengubah atau menghapus jadwal shift kerja.',
            ],
            'steps' => [
                'Klik tombol "Tambah Jam Kerja" di kanan atas.',
                'Beri kode dan nama shift (contoh: "Shift Pagi Outlet").',
                'Tentukan Jam Masuk dan Jam Pulang kerja.',
                'Tentukan batas awal mulai boleh absen (misal: 30 menit sebelum jam masuk).',
                'Tentukan batas toleransi menit (misal: 15 menit). Staf yang absen setelah toleransi ini akan ditandai sebagai Terlambat.',
                'Klik "Simpan" untuk menerapkan jadwal shift.',
            ],
            'components' => [
                'Jam Masuk & Jam Pulang' => 'Jam resmi staf mulai bekerja dan jam resmi staf selesai bekerja.',
                'Batas Awal Mulai Absen' => 'Waktu paling awal sistem mulai menerima absensi masuk dari karyawan.',
                'Batas Akhir Absen Masuk' => 'Waktu penutupan presensi masuk jika staf tidak hadir.',
                'Batas Toleransi Keterlambatan' => 'Jumlah menit kelonggaran waktu sebelum sistem mencatat staf sebagai "Terlambat".',
            ],
            'tips' => [
                'Berikan batas awal mulai absen sekitar 30–60 menit sebelum jam kerja agar staf yang datang lebih pagi dapat langsung melakukan presensi dengan tenang.',
            ],
            'warnings' => 'Perubahan jam masuk dan pulang pada shift yang sedang aktif akan langsung memengaruhi perhitungan keterlambatan dan jam lembur karyawan hari ini.',
        ],

        'laporan_presensi' => [
            'id' => 'laporan_presensi',
            'pattern' => ['laporan/presensi', 'laporan/presensi/*'],
            'title' => 'Laporan Rekapitulasi Presensi',
            'subtitle' => 'Pencetakan laporan kehadiran berkala dan ekspor ke Microsoft Excel',
            'icon' => 'ti ti-file-spreadsheet',
            'badge' => 'Laporan',
            'about' => 'Halaman Laporan Presensi digunakan untuk menyusun rekapitulasi kehadiran staf selama periode tertentu (misalnya mingguan, bulanan, atau tahunan). Rekap mencakup total hari hadir, keterlambatan, jam kerja, izin, sakit, cuti, hingga alpa, dan dapat dicetak atau diunduh ke Excel.',
            'actions' => [
                'Memilih rentang periode tanggal laporan yang ingin ditarik datanya.',
                'Menyaring laporan berdasarkan satu cabang tertentu atau seluruh cabang.',
                'Menyaring laporan berdasarkan divisi departemen tertentu.',
                'Memilih laporan untuk satu staf tertentu atau seluruh staf sekaligus.',
                'Mencetak laporan ke format lembar cetak printer / PDF.',
                'Mengunduh laporan rekapitulasi lengkap ke dalam berkas Microsoft Excel (.xlsx).',
            ],
            'steps' => [
                'Pilih Cabang dan Departemen yang ingin Anda buatkan laporannya.',
                'Pilih Karyawan tertentu jika hanya ingin melihat perorangan, atau biarkan kosong untuk seluruh karyawan.',
                'Tentukan tanggal mulai ("Dari Tanggal") dan tanggal akhir ("Sampai Tanggal") periode laporan.',
                'Klik tombol "Cetak Laporan" untuk membuka lembaran cetak PDF siap print.',
                'Klik tombol "Export Excel" jika Anda ingin mengolah angka laporan lebih lanjut di spreadsheet.',
            ],
            'components' => [
                'Filter Periode Tanggal' => 'Batas awal dan batas akhir perhitungan rekapan absensi.',
                'Pilihan Staf / Cabang' => 'Memungkinkan pembuatan rekap per individu staf atau secara menyeluruh satu outlet.',
                'Tombol Cetak Laporan' => 'Membuka tab baru berisi formulir cetak bertanda tangan yang rapi.',
                'Tombol Export Excel' => 'Mengunduh tabel rekapan dalam format lembar kerja Excel.',
            ],
            'tips' => [
                'Pastikan seluruh pengajuan izin, sakit, dan dispensasi pada bulan bersangkutan sudah disetujui terlebih dahulu sebelum Anda mengunduh laporan rekap untuk perhitungan gaji.',
            ],
            'warnings' => null,
        ],

        'laporan_cuti' => [
            'id' => 'laporan_cuti',
            'pattern' => ['laporan/cuti', 'laporan/cuti/*'],
            'title' => 'Laporan Rekapitulasi Cuti',
            'subtitle' => 'Rekap penggunaan hak cuti tahunan dan sisa saldo cuti staf',
            'icon' => 'ti ti-report-analytics',
            'badge' => 'Laporan',
            'about' => 'Halaman Laporan Cuti digunakan untuk melihat rekapitulasi pemakaian cuti seluruh staf dalam satu tahun berjalan. Di sini terlihat berapa hari jatah cuti yang telah digunakan dan berapa hari sisa cuti yang masih dimiliki masing-masing karyawan.',
            'actions' => [
                'Memilih tahun periode laporan cuti yang ingin ditinjau.',
                'Menyaring rekap cuti berdasarkan cabang outlet dan departemen.',
                'Mencetak rekapitulasi saldo cuti ke printer atau PDF.',
                'Mengunduh laporan rekapitulasi cuti ke berkas Microsoft Excel.',
            ],
            'steps' => [
                'Pilih cabang dan departemen yang ingin Anda lihat datanya.',
                'Pilih tahun laporan yang diinginkan.',
                'Klik "Cetak Laporan" untuk tampilan cetak fisik, atau klik "Export Excel" untuk menyimpannya sebagai file spreadsheet.',
            ],
            'components' => [
                'Pilihan Tahun' => 'Menentukan tahun kalender perhitungan kuota cuti.',
                'Kolom Total Cuti Diambil' => 'Jumlah hari cuti yang sudah pernah disetujui oleh manajemen.',
                'Kolom Sisa Saldo Cuti' => 'Sisa kuota hak cuti staf yang masih tersisa.',
            ],
            'tips' => [
                'Gunakan laporan ini menjelang akhir tahun untuk mengevaluasi hak cuti staf yang belum terpakai.',
            ],
            'warnings' => null,
        ],

        'generalsetting' => [
            'id' => 'generalsetting',
            'pattern' => ['generalsetting', 'generalsetting/*'],
            'title' => 'Pengaturan Umum Sistem',
            'subtitle' => 'Konfigurasi nama aplikasi, logo, warna tema, dan parameter presensi',
            'icon' => 'ti ti-settings-cog',
            'badge' => 'Pengaturan',
            'about' => 'Halaman Pengaturan Umum adalah pusat kendali sistem untuk menentukan identitas aplikasi dan parameter penting kehadiran, seperti nama perusahaan, logo, warna tampilan admin, radius standar absen, serta sensitivitas pencocokan wajah (face recognition).',
            'actions' => [
                'Mengubah Nama Aplikasi dan Nama Perusahaan yang tampil di halaman login dan navbar.',
                'Mengunggah logo resmi perusahaan yang tampil di sidebar menu dan laporan.',
                'Mengatur Warna Tema Utama (Primary) dan Warna Sekunder (Secondary) antarmuka admin.',
                'Menentukan Jarak Radius Standar (dalam meter) untuk presensi GPS.',
                'Mengatur Tingkat Akurasi Pengenalan Wajah (Face Recognition Threshold).',
                'Menyimpan seluruh konfigurasi sistem secara terpusat.',
            ],
            'steps' => [
                'Ubah teks Nama Aplikasi atau Nama Perusahaan pada kolom yang tersedia.',
                'Pilih warna tema utama dan sekunder menggunakan pemilih warna (color picker) jika ingin menyesuaikan dengan warna khas perusahaan.',
                'Atur angka radius standar dan ambang batas pencocokan wajah jika diperlukan.',
                'Gulir ke bawah dan klik tombol "Simpan Pengaturan" untuk menerapkan perubahan ke seluruh sistem.',
            ],
            'components' => [
                'Nama Aplikasi' => 'Judul sistem yang tampil pada bilah peramban dan judul laporan.',
                'Logo Perusahaan' => 'Berkas gambar lambang perusahaan yang akan disematkan di pojok kiri atas aplikasi.',
                'Warna Tema Utama & Sekunder' => 'Menentukan palet warna tombol, navigasi, dan aksen grafis di seluruh sistem.',
                'Ambang Batas Wajah (Threshold)' => 'Tingkat ketelitian algoritma dalam mencocokkan wajah staf saat presensi selfie.',
            ],
            'tips' => [
                'Gunakan logo dengan format gambar PNG berlatar transparan agar terlihat rapi dan elegan pada sidebar admin.',
                'Sebaiknya biarkan nilai ambang batas wajah pada angka rekomendasi sistem kecuali jika Anda memiliki panduan teknis khusus.',
            ],
            'warnings' => 'Perubahan pada halaman ini memengaruhi tampilan dan pengaturan operasional di seluruh akun pengguna dan seluruh outlet.',
        ],

        'users' => [
            'id' => 'users',
            'pattern' => ['users', 'users/*'],
            'title' => 'Manajemen Pengguna Admin',
            'subtitle' => 'Pengelolaan akun login administrator, hak akses role, dan kata sandi',
            'icon' => 'ti ti-user-check',
            'badge' => 'Keamanan Akun',
            'about' => 'Halaman Manajemen Pengguna digunakan untuk mengelola akun-akun yang memiliki izin masuk ke Area Admin (seperti akun Super Admin, Admin Personalia, Admin Cabang, atau Pimpinan). Di sini Anda dapat membuat akun admin baru, mengatur role (hak akses), dan mengganti kata sandi akun.',
            'actions' => [
                'Melihat daftar seluruh akun pengguna yang memiliki akses ke dashboard admin.',
                'Mendaftarkan akun administrator baru.',
                'Mengubah nama, alamat email login, atau penugasan cabang admin bersangkutan.',
                'Menetapkan peran (Role) pengguna (contoh: Super Admin, Admin, atau GM Administrasi).',
                'Mengganti atau mereset kata sandi (password) akun pengguna jika diperlukan.',
                'Menghapus akun pengguna yang sudah tidak berhak mengakses area admin.',
            ],
            'steps' => [
                'Klik tombol "Tambah Pengguna" di kanan atas untuk mendaftarkan akun admin baru.',
                'Ketikkan nama pengguna, alamat email aktif, kata sandi awal yang aman, dan pilih Role (peran) yang sesuai.',
                'Tentukan cabang yang dapat diakses oleh akun tersebut (khusus untuk admin cabang).',
                'Klik "Simpan" untuk mengaktifkan akun baru.',
                'Untuk mengganti kata sandi staf admin, klik tombol ikon kunci (Ganti Password) pada baris akun bersangkutan.',
            ],
            'components' => [
                'Email Pengguna' => 'Alamat surat elektronik yang digunakan untuk masuk (login) ke dalam sistem.',
                'Role / Hak Akses' => 'Tingkatan wewenang pengguna dalam mengakses menu-menu sistem.',
                'Tombol Ganti Password' => 'Formulir untuk memperbarui kata sandi akun jika staf lupa kata sandinya.',
            ],
            'tips' => [
                'Gunakan kata sandi yang kuat dengan kombinasi huruf besar, huruf kecil, dan angka.',
                'Berikan role sesuai dengan tanggung jawab staf bersangkutan (prinsip kehati-hatian akses data).',
            ],
            'warnings' => 'Jangan pernah membagikan email dan kata sandi akun administrator kepada pihak yang tidak berkepentingan demi menjaga keamanan data kepegawaian perusahaan.',
        ],

        'permissiongroups' => [
            'id' => 'permissiongroups',
            'pattern' => ['permissiongroups', 'permissiongroups/*'],
            'title' => 'Grup Hak Akses Sistem',
            'subtitle' => 'Pengelompokan kategori izin akses fitur aplikasi',
            'icon' => 'ti ti-folder-check',
            'badge' => 'Hak Akses',
            'about' => 'Halaman Grup Hak Akses digunakan untuk mengelompokkan izin-izin teknis ke dalam kelompok menu yang teratur (seperti kelompok Karyawan, Presensi, Pengajuan Izin, dan Laporan) agar pengaturan izin pengguna lebih terstruktur.',
            'actions' => [
                'Melihat daftar kelompok izin akses yang ada.',
                'Menambah kelompok izin baru.',
                'Mengubah nama kelompok hak akses.',
                'Menghapus kelompok yang tidak digunakan.',
            ],
            'steps' => [
                'Klik "Tambah Grup" untuk membuat kelompok baru.',
                'Ketikkan nama grup dan deskripsi singkat.',
                'Klik "Simpan" untuk menyimpan grup.',
            ],
            'components' => [
                'Nama Grup' => 'Kategori menu tempat izin-izin fitur dikelompokkan.',
            ],
            'tips' => [
                'Halaman ini dikhususkan bagi Super Admin untuk pemeliharaan struktur hak akses sistem.',
            ],
            'warnings' => 'Hindari menghapus grup hak akses yang sedang menaungi izin-izin aktif aplikasi.',
        ],

        'permissions' => [
            'id' => 'permissions',
            'pattern' => ['permissions', 'permissions/*'],
            'title' => 'Daftar Izin & Hak Akses',
            'subtitle' => 'Konfigurasi izin teknis setiap fitur dan tombol pada aplikasi',
            'icon' => 'ti ti-shield-lock',
            'badge' => 'Hak Akses',
            'about' => 'Halaman Daftar Izin digunakan oleh Super Admin untuk melihat dan mengonfigurasi izin akses detail setiap fitur dalam aplikasi (misalnya: izin melihat data karyawan, izin menambah data, izin menyetujui cuti, izin menghapus presensi).',
            'actions' => [
                'Melihat daftar seluruh izin teknis yang mengatur wewenang di aplikasi.',
                'Menambah izin fitur baru.',
                'Mengubah nama atau grup izin.',
                'Menghapus izin yang sudah tidak digunakan.',
            ],
            'steps' => [
                'Klik tombol "Tambah Permission" jika sistem memiliki modul fitur baru yang ingin dibatasi hak aksesnya.',
                'Masukkan nama teknis izin (misal: "laporan.presensi") dan pilih grup menu terkait.',
                'Klik "Simpan" untuk mendaftarkan izin ke dalam sistem keamanan.',
            ],
            'components' => [
                'Nama Permission' => 'Kode pengenal izin fitur di dalam kode sistem.',
                'Grup Permission' => 'Kategori menu yang memuat izin bersangkutan.',
            ],
            'tips' => [
                'Izin ini bekerja secara otomatis bersama sistem Role Pengguna.',
            ],
            'warnings' => 'Mengubah atau menghapus nama izin yang sedang digunakan di aplikasi dapat menyebabkan tombol atau halaman tertentu tidak dapat dibuka oleh staf admin.',
        ],

        'backup' => [
            'id' => 'backup',
            'pattern' => ['backup', 'backup/*'],
            'title' => 'Backup & Restore Database',
            'subtitle' => 'Pencadangan arsip data sistem dan pemulihan database secara aman',
            'icon' => 'ti ti-database-export',
            'badge' => 'Pemeliharaan',
            'about' => 'Halaman Backup & Restore Database digunakan untuk menjaga keamanan seluruh data perusahaan. Anda dapat mengunduh berkas salinan cadangan (backup file .sql) ke komputer pribadi sebagai arsip aman, serta mengembalikan (restore) data jika terjadi insiden teknis.',
            'actions' => [
                'Mengunduh salinan cadangan database sistem (.sql) saat ini ke komputer pribadi.',
                'Menyimpan arsip data secara berkala untuk keperluan keamanan dan kepatuhan data.',
                'Melakukan pemulihan (restore) database dari file salinan cadangan yang pernah diunduh sebelumnya.',
            ],
            'steps' => [
                'Untuk membuat cadangan data, klik tombol besar "Download Backup Database (.sql)". Sistem akan menyiapkan berkas dan peramban Anda akan mulai mengunduh file cadangan.',
                'Simpan berkas hasil download tersebut di tempat penyimpanan yang aman (misalnya: flashdisk atau Google Drive perusahaan).',
                'Jika ingin memulihkan data dari berkas lama, klik tombol pilih file pada kartu Restore, pilih berkas .sql cadangan Anda, lalu klik "Mulai Restore Data".',
            ],
            'components' => [
                'Kartu Backup Data' => 'Area untuk memicu pembuatan dan pengunduhan salinan database terbaru.',
                'Kartu Restore Data' => 'Area untuk mengunggah berkas salinan database lama guna mengembalikan kondisi sistem.',
            ],
            'tips' => [
                'Sangat disarankan melakukan pengunduhan backup database secara berkala (misalnya setiap akhir pekan atau setiap akhir bulan sebelum proses penggajian).',
                'Beri nama atau simpan berkas backup dengan mencantumkan tanggal pengunduhan agar mudah dikenali saat dibutuhkan.',
            ],
            'warnings' => 'PERHATIAN PENTING: Proses "Restore Database" akan MENIMPA dan MENGGANTIKAN seluruh data yang ada saat ini dengan data yang ada di dalam berkas cadangan. Lakukan restore hanya jika benar-benar diarahkan oleh tim teknis pimpinan.',
        ],
    ],
];
